name: Build examples
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build-examples:
    name: Build ${{ matrix.working_directory }} for ${{ matrix.idf_target }} on ${{ matrix.idf_ver }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        idf_ver: ["release-v5.2", "latest"]
        idf_target: ["esp32", "esp32s2", "esp32s3", "esp32c2", "esp32c3"]
        working_directory: ["get_start"]
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: mlx90614
          submodules: 'true'
      - name: esp-idf build
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        shell: bash
        working-directory: mlx90614/examples/${{ matrix.working_directory }}
        run: |
          . ${IDF_PATH}/export.sh
          export PEDANTIC_FLAGS="-DIDF_CI_BUILD -Werror -Werror=deprecated-declarations -Werror=unused-variable -Werror=unused-but-set-variable -Werror=unused-function"
          export EXTRA_CFLAGS="${PEDANTIC_FLAGS} -Wstrict-prototypes"
          export EXTRA_CXXFLAGS="${PEDANTIC_FLAGS}"
          idf.py build
